name: Build Cross OS

on:
  push:
    branches:
      - master
  pull_request:

jobs:

  cross:
    name: Go
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: ${{ github.workspace }}/go/src/github.com/traefik/yaegi

    strategy:
      matrix:
        go-version: [ oldstable, stable ]
        os: [ubuntu-latest, macos-latest, windows-latest]

        include:
          - os: ubuntu-latest
            go-path-suffix: /go
          - os: macos-latest
            go-path-suffix: /go
          - os: windows-latest
            go-path-suffix: \go

    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
        with:
          path: go/src/github.com/traefik/yaegi

      # https://github.com/marketplace/actions/setup-go-environment
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version: ${{ matrix.go-version }}
          stable: true

      - name: Setup GOPATH
        run: go env -w GOPATH=${{ github.workspace }}${{ matrix.go-path-suffix }}

# TODO fail on windows
#      - name: Tests
#        run: go test -v -cover ./...
#        env:
#          GOPATH: ${{ github.workspace }}${{ matrix.go-path }}

      - name: Build
        run: go build -race -v -ldflags "-s -w" -trimpath
